version: "~> 1.0"
os: linux
dist: bionic
language: python
cache:
  directories:
  - "/home/travis/.vagrant.d/boxes"
notifications:
  email:
    on_success: never
    on_failure: never
  slack:
    if: branch = master
    rooms:
      secure: nN90UuGNPfq7n0BdJI4oI7vsKIT3wUu7V3VoE28f8pXkJLXBuYocUvuQDaGY+Q3q3BSBNQTQhNRS4El9Ya7oR6zXMCuqQQ/ho1IRkynzyryzTnZR2duWx6BbIJaHKO1VtGgQNSdGNkCXNVokOlBh52WIq5Xd6vpIEw+p6Z+qjJj/EFOg9KXugcTCX0CR3a5ykxOWJ7ldVLPKMUCfN7r9NnpF1CDxugrybSZ9R62dPU/W+O54bsn6RcMMpL4ayeu9SLMi2/MS/jj37r2/p9o8p/Ckq3GeFR1t536/gS9ng6k8ZDp/7UZJ3p0YNgpCwt37+DViU1yQKnUHGAV21IWTG4wpi06HPIDum5u6EKGrIfBddgisCP7lV43De/Y8QqgcY981Cd3eBh3iAWOAcWWPmfGucn87q/DEU5QFEuOTDzXqYjulEnjHhxrW5NnNi7c83R9WZLxbldBuIIhWWSd8ZZrIFHobr7iYAhAM/j77k1w26txL8+TXWdZ8oxWN01BKjhzMscIjVpoVNUr+Y3BG2pqQTTrw625l+HwdyS0v7fj/Vb/XeRMuTzPtsoS27U3ughqZuYJhv2k8zE2zs+ipPnXiUCmLKEiAP5UTbX3zs8//E0h0kVX79oxFsxgFRHfp3kCaKoKCyqnj/FWJBYZKTtGk/WYolEXPYNxntS/exwE=
    template:
    - "%{commit_subject}"
    - build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) @%{branch}
    - by %{author} %{result} in %{duration}
    on_success: change
    on_failure: always
env:
  global: 
install:
- sudo apt-get update && sudo apt-get install -y bridge-utils dnsmasq-base ebtables
  libvirt-bin libvirt-dev qemu-kvm qemu-utils ruby-dev
- sudo wget -nv https://releases.hashicorp.com/vagrant/2.2.7/vagrant_2.2.7_x86_64.deb
- sudo dpkg -i vagrant_2.2.7_x86_64.deb
- vagrant --version
- sudo vagrant plugin install vagrant-libvirt
script:
- sudo vagrant validate
- sudo vagrant up --provider=libvirt
- sudo vagrant destroy -f
