version: "~> 1.0"
os: linux
dist: bionic
language: python
cache:
  directories:
  - "/home/travis/.vagrant.d/boxes"
notifications:
  email:
    on_success: never
    on_failure: never
  slack:
    if: branch = master
    rooms:
      secure: NGxZDKukFf9KwNRiAZXqJR+/SDZUBl0AaNThOL6F0Aj2c1Mp9Tp6N5+5Oubj8seO4UMpkRWUS3xQCtrlS8HYvCdDN8/jW+unUAnuc9pcgA86qFkGsfYKG4mabHqJfUKjWxCHKG1q1XIdULcahzzcKGLqjfuN8I/meemb7cxiCJpJItjd4L7vDFbaU1ALstzUJ3kDqfnjSazjKBgs6xMoajjP3mBao/zCoMQBkeVZdtjMqspDZP4EEs6NJsI8QmjeGxtV8SJ3ErqlrvvsE2YLrF970D2VWaFmGpm6uPQUN9n+R5/l0HM/evgKZB8za0uOYZcwAV23Ldkh7sowXZXXthbpH7Lu5TmD4Lt3HwbNet6D7pjxb+9kJfNlvyemWDETbMDP2oewMGeJ4J0GT126EeYJpgFcQU/PYMWMZGmMbTc8NoEfg7sf8sb+DKIp9EfUn8UHvsStSb/9HHQaeTePvRsT4ZtMbPlP+sq/wFYaVOHUXl/04dt15yykzTdfZX9SEO0zlnIxL4svBcXOsPHd4Odm2stxiB0iP+KUts2rGgzUgzkFdjEUg+afbqQN/IDc1nUdFQrZGzABBPJ7dylZiPhGXvpDjeX9yECevMX1y3eK9jHNPsi5xSWk9i6sE01GtlUAZW907rTxQE4hPdcuq6zJGcxjefrJI23In48yGQs=
    template:
    - "%{commit_subject}"
    - build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) @%{branch}
    - by %{author} %{result} in %{duration}
    on_success: change
    on_failure: always
env:
  global: 
install:
- sudo apt-get update && sudo apt-get install -y bridge-utils dnsmasq-base ebtables
  libvirt-bin libvirt-dev qemu-kvm qemu-utils ruby-dev
- sudo wget -nv https://releases.hashicorp.com/vagrant/2.2.7/vagrant_2.2.7_x86_64.deb
- sudo dpkg -i vagrant_2.2.7_x86_64.deb
- vagrant --version
- sudo vagrant plugin install vagrant-libvirt
script:
- sudo vagrant up --provider=libvirt
- sudo vagrant destroy -f
