---
- hosts: all
  become: true
  pre_tasks:
    - name: Install python for Ansible
      raw: test -e /usr/bin/python3 || (yum install -y python3)
      changed_when: false
  vars:
    okd_public_hostname: "192.168.0.5"
  roles:
    - role: gepardec.basics
    - role: gepardec.ntp
    - role: gepardec.okd
    