---
- hosts: all
  pre_tasks:
    - name: Install python for Ansible
      raw: test -e /usr/bin/python3 || (yum install -y python3)
      become: true
      changed_when: false
  roles:
  - gepardec.ntp
  - gepardec.okd
