---
- hosts: all
  become: true
  pre_tasks:
    - name: Install python for Ansible
      raw: test -e /usr/bin/python3 || (yum install -y python3)
      changed_when: false
    - debug: 
        var: ansible_facts
        verbosity: 2
    - debug: 
        var: ansible_facts['eth1']['ipv4']['address']
        verbosity: 1
  tasks:
    - include_role:
        name: gepardec.basics
    - include_role:
        name: gepardec.ntp
    - include_role:
        name: gepardec.okd
      vars: 
        okd_public_hostname: "{{ ansible_facts['eth1']['ipv4']['address'] }}"
...
    