---
- hosts: all
  become: true
  pre_tasks:
    - name: Install python for Ansible
      raw: test -e /usr/bin/python3 || (yum install -y python3)
      changed_when: false
    - debug: 
        var: ansible_facts
        verbosity: 2
    - debug: 
        # https://stackoverflow.com/questions/31310688/conditionally-define-variable-in-ansible
        msg: "{{ ansible_facts['eth1']['ipv4']['address'] if ansible_facts['virtualization_type'] == 'virtualbox' else ansible_facts['eth0']['ipv4']['address'] | default('127.0.0.1')}}"
        verbosity: 1
  tasks:
    - name: create docker config.json
      raw: mkdir -p /root/.docker && echo "{}" > /root/.docker/config.json
      become: true
      changed_when: false
    - include_role:
        name: gepardec.basics
    - include_role:
        name: gepardec.ntp
    - include_role:
        name: gepardec.okd
      vars: 
        okd_public_hostname: "{{ ansible_facts['eth0']['ipv4']['address'] if ansible_facts['virtualization_type'] == 'virtualbox' else ansible_facts['eth1']['ipv4']['address'] | default('127.0.0.1')}}"
...
    