# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ feature/actions ]
  # pull_request:
  #   branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  validate:
    runs-on: [self-hosted, windows]
    steps:
    - name: Validate Vagrantfile
      run: vagrant validate
      
  vagrant:
    runs-on: [self-hosted, windows]
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Start vm
      run: vagrant up

    # Runs a set of commands using the runners shell
    - name: Stop vm
      run: vagrant destroy -f
      if: always()
